### ISSUE TITLE
logo的地址只能写在线地址吗

### ISSUE THREAD

**Issue by lwjcjmx123** [HerbLuo/qr-code-with-logo#2]
用了本地的相对路径地址，似乎取不到？

**Comment by HerbLuo** [comment]
**支持**本地图片的。

* 如果使用了`webpack`等构建工具的话，**不建议用相对地址**，
因为那样的话，可能会导致打包后出现问题，推荐的方案见 **示例1**。

* 如果没有使用构建工具，应该是可以**直接写**相对地址的。

* 如果对上面的解释有疑虑，可以将**详细代码**贴出来讨论。

-------
示例1：

```javascript
import LocalImage from './AvatarGitHub.png'

QrCodeWithLogo.toCanvas({
  canvas,
  content: 'http://cdn.blog.cloudself.cn',
  width: 380,
  logo: {
    src: LocalImage, 
  },
})
```

此时，需要安装一下`url-loader`并且在`webpack`的配置中需添加如下配置：
```javascript
{
  test: /\.(svg|png|jpg)$/,
  use: 'url-loader?limit=4096',
}
```

-----
回复晚了抱歉。

**Comment by HerbLuo** [comment]
> 用了本地的相对路径地址，似乎取不到？

**支持**本地图片的。

* 如果使用了`webpack`等构建工具的话，**不建议用相对地址**，
因为那样的话，可能会导致打包后出现问题，推荐的方案见 **示例1**。

* 如果没有使用构建工具，应该是可以**直接写**相对地址的。

* 如果对上面的解释有疑虑，可以将**详细代码**贴出来讨论。

-------
示例1：

```javascript
import LocalImage from './AvatarGitHub.png'

QrCodeWithLogo.toCanvas({
  canvas,
  content: 'http://cdn.blog.cloudself.cn',
  width: 380,
  logo: {
    src: LocalImage, 
  },
})
```

此时，需要安装一下`url-loader`并且在`webpack`的配置中需添加如下配置：
```javascript
{
  test: /\.(svg|png|jpg)$/,
  use: 'url-loader?limit=4096',
}
```

-----
回复晚了抱歉。

**Comment by lwjcjmx123** [comment]
@HerbLuo 我用的本地绝对路径解决了这个问题，就是之前相对路径 webpack 打包后的路径不同，所以取不到，后面改为绝对路径，加上其他地方也用到了这张图片，然后webpack一起打包进去了实现了
